apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ip-changer
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ip-changer
    spec:
      containers:
      - name: ip-changer
        image: ityer/k8s-ip-changer:v2
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: ip-changer
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 4000
    protocol: TCP
  selector:
    app: ip-changer
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: recyclerjob
spec:
  schedule: "*/20 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: recyclerjob
            image: appropriate/curl
            args:
            - /bin/sh
            - -ec
            - curl ip-changer.default.svc.cluster.local:4000/recycle
          restartPolicy: Never               